import torch
from transformers import AutoTokenizer
from pathlib import Path
from typing import Optional

from config import LLMConfig
from core.critic import CriticFeedback, Critic
from models.base_llm import BaseLLM
from utils.logger import get_logger

logger = get_logger(__name__)

# Output dict maps from integer class to verdict string
IDX_TO_VERDICT = {
    0: "poor",
    1: "acceptable",
    2: "good",
    3: "excellent"
}

class LearnedCritic:
    """
    Fast, local, and learned evaluator that predicts score and verdict
    using a fine-tuned small Transformer (e.g. MiniLM).
    
    Acts as a first-pass hybrid critic: if it detects serious issues, 
    it can fall back to the slow LLM-based Critic to generate explanations.
    """
    def __init__(self, model_dir: str, llm_fallback: Optional[BaseLLM], config: LLMConfig):
        """
        model_dir: path to saved `learned_critic.pt` and tokenizer base name.
        llm_fallback: if provided, hybrid mode is enabled.
        """
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.tokenizer = AutoTokenizer.from_pretrained("microsoft/MiniLM-L12-H384-uncased") # Same as training
        
        # We need to import the class definition to load weights
        from scripts.train_critic import LearnedCriticModel
        
        self.model = LearnedCriticModel()
        
        model_path = Path(model_dir) / "learned_critic.pt"
        if model_path.exists():
            self.model.load_state_dict(torch.load(model_path, map_location=self.device, weights_only=True))
        else:
            logger.warning(f"LearnedCritic weights not found at {model_path}. Using untrained weights.")
            
        self.model.to(self.device)
        self.model.eval()
        
        self._llm_fallback = llm_fallback
        self._fallback_critic = Critic(llm_fallback, config) if llm_fallback else None
        
    def critique(self, query: str, answer: str) -> CriticFeedback:
        """
        Evaluate answer with the Learned model.
        Falls back to LLM if score is poor or acceptable, and fallback enabled.
        """
        text = f"Query: {query} [SEP] Answer: {answer}"
        encoding = self.tokenizer(
            text,
            padding=True,
            truncation=True,
            max_length=512,
            return_tensors='pt'
        ).to(self.device)
        
        with torch.no_grad():
            verdict_logits, score_pred = self.model(encoding['input_ids'], encoding['attention_mask'])
            
        # Parse outputs
        verdict_idx = torch.argmax(verdict_logits, dim=-1).item()
        verdict = IDX_TO_VERDICT.get(verdict_idx, "poor")
        
        # Calculate confidence from softmax temperature
        probs = torch.softmax(verdict_logits, dim=-1)
        confidence = probs[0, verdict_idx].item()
        
        score = score_pred.item()
        
        logger.info(f"LearnedCritic: Predicted Score: {score:.2f}, Verdict: {verdict}, Confidence: {confidence:.2f}")
        
        # --- HYBRID LOGIC ---
        # If the answer needs refinement (score < 8.5) and a fallback is present, 
        # we need specific `improvement_actions` which the small model cannot generate.
        if score < 8.5 and self._fallback_critic is not None:
            logger.info("LearnedCritic: Generating specific feedback using slow LLM Critic...")
            return self._fallback_critic.critique(query, answer)

        # Fast path (Excellent answer, or no fallback provided)
        return CriticFeedback(
            factual_errors=[],
            hallucinations=[],
            missing_concepts=[],
            logical_flaws=[],
            improvement_actions=[],
            score=min(max(score, 0.0), 10.0),
            raw_llm_score=score,
            confidence=confidence,
            verdict=verdict,
            raw_response="[Generated by tiny Learned Critic]"
        )
